# Generated by Django 3.2.9 on 2021-11-07 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('vetted', models.BooleanField()),
                ('assistance_type', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrgUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FallInApp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('needs', models.CharField(max_length=100)),
                ('urgency', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=1024)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FallInApp.chatroom')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FallInApp.orguser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=1024)),
                ('chatroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FallInApp.chatroom')),
                ('org_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FallInApp.orguser')),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='org_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FallInApp.orguser'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FallInApp.user'),
        ),
    ]
